### ISSUE TITLE
entity_link does not function

### ISSUE THREAD

**Issue by Quackers29** [latibro/Automation-Mod#15]
entity_link does not function on OC with the latest release, Alpha 5

![image](https://user-images.githubusercontent.com/11053436/107977030-5a9c8100-6fb2-11eb-8067-98e2111440e3.png)

**Comment by latibro** [comment]
@Gazer29 did you have an "entity link card" in the entity link box?

And was the card paired to an entity?

Note to self: We need better error messages here :-)

**Comment by Quackers29** [comment]
The way I assumed to use the entity card was:
Get in the train, left click with the entity card
the 'entity id stored:' pops up in chat
I right click the entity link box, nothing happens but I assume it is linked?

**Comment by latibro** [comment]
Oh you didn't notice that the box had an GUI / inventory for the card?

**Comment by Quackers29** [comment]
O, no, it has no inventory to me. I've tried opening it with a free hand etc.

**Comment by Quackers29** [comment]
When I try to right click on the Entity link box, I get this error.
`[17:51:40] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: groovy.lang.MissingPropertyException: No such property: inventory for class: net.minecraft.entity.player.EntityPlayerMP
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: groovy.lang.MissingPropertyException: No such property: inventory for class: net.minecraft.entity.player.EntityPlayerMP
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65) ~[ScriptBytecodeAdapter.class:3.0.7]
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65) ~[GetEffectivePojoPropertySite.class:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329) ~[AbstractCallSite.class:3.0.7]
	at latibro.automation.linkbox.PlayerContainer$PlayerSlot.<init>(PlayerContainer.groovy:57) ~[PlayerContainer$PlayerSlot.class:?]
	at latibro.automation.linkbox.PlayerContainer$PlayerHotbarSlot.<init>(PlayerContainer.groovy:66) ~[PlayerContainer$PlayerHotbarSlot.class:?]
	at sun.reflect.GeneratedConstructorAccessor138.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_231]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72) ~[CachedConstructor.class:3.0.7]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.class:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:304) ~[AbstractCallSite.class:3.0.7]
	at latibro.automation.linkbox.PlayerContainer.addPlayerHotbarSlotsToContainer(PlayerContainer.groovy:16) ~[PlayerContainer.class:?]
	at latibro.automation.linkbox.PlayerContainer$addPlayerHotbarSlotsToContainer.callCurrent(Unknown Source) ~[?:?]
	at latibro.automation.linkbox.PlayerContainer.addPlayerSlotsToContainer(PlayerContainer.groovy:28) ~[PlayerContainer.class:?]
	at latibro.automation.linkbox.entity.EntityLinkBoxContainer.<init>(EntityLinkBoxContainer.groovy:13) ~[EntityLinkBoxContainer.class:?]
	at latibro.automation.proxy.ScreenProxy.getServerGuiElement(ScreenProxy.groovy:24) ~[ScreenProxy.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at latibro.automation.linkbox.entity.EntityLinkBoxBlock.func_180639_a(EntityLinkBoxBlock.groovy:56) ~[EntityLinkBoxBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
`

**Comment by latibro** [comment]
Hmm... will try to reproduce...
